CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_HR_EMP_OPEN_BIKE_REQ" ("REQUEST_ID", "EMP_ID", "REQUEST_TYPE", "REQUEST_STATUS", "PRIORITY", "REQUESTED_DT", "REQUESTED_BY", "REQUIRED_BY_DT", "CURRENT_BIKE_ID", "ASSIGNED_BIKE_ID", "BIKE_ASSIGNMENT_ID", "REQUESTED_PROJECT_ID", "REQUESTED_CITY_ID", "REASON_CODE", "REQUEST_REMARKS", "REJECTION_REASON", "CLOSED_BY", "CLOSED_DT", "CREATED_BY", "CREATED_DT", "UPDATED_BY", "UPDATED_DT", "RN") AS 
  with r as (
    select br.*,
           row_number() over (
               partition by br.emp_id
               order by br.requested_dt desc, br.request_id desc
           ) rn
      from hr_bike_requests br
     where br.request_status in ('OPEN','IN_PROGRESS')
)
select "REQUEST_ID","EMP_ID","REQUEST_TYPE","REQUEST_STATUS","PRIORITY","REQUESTED_DT","REQUESTED_BY","REQUIRED_BY_DT","CURRENT_BIKE_ID","ASSIGNED_BIKE_ID","BIKE_ASSIGNMENT_ID","REQUESTED_PROJECT_ID","REQUESTED_CITY_ID","REASON_CODE","REQUEST_REMARKS","REJECTION_REASON","CLOSED_BY","CLOSED_DT","CREATED_BY","CREATED_DT","UPDATED_BY","UPDATED_DT","RN"
  from r
 where rn = 1;
