CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_HR_EMP_OPEN_SIM_REQ" ("REQUEST_ID", "EMP_ID", "REQUEST_TYPE", "REQUEST_STATUS", "PRIORITY", "REQUESTED_DT", "REQUESTED_BY", "REQUIRED_BY_DT", "REQUESTED_PROJECT_ID", "REQUESTED_CITY_ID", "CURRENT_SIM_ID", "ASSIGNED_SIM_ID", "SIM_ASSIGN_ID", "REASON_CODE", "REQUEST_REMARKS", "REJECTION_REASON", "CANCELLATION_REASON", "CLOSED_BY", "CLOSED_DT", "CREATED_BY", "CREATED_DT", "UPDATED_BY", "UPDATED_DT", "RN") AS 
  with r as (
    select sr.*,
           row_number() over (
               partition by sr.emp_id
               order by sr.requested_dt desc, sr.request_id desc
           ) rn
      from hr_sim_requests sr
     where sr.request_status in ('OPEN','IN_PROGRESS')
)
select "REQUEST_ID","EMP_ID","REQUEST_TYPE","REQUEST_STATUS","PRIORITY","REQUESTED_DT","REQUESTED_BY","REQUIRED_BY_DT","REQUESTED_PROJECT_ID","REQUESTED_CITY_ID","CURRENT_SIM_ID","ASSIGNED_SIM_ID","SIM_ASSIGN_ID","REASON_CODE","REQUEST_REMARKS","REJECTION_REASON","CANCELLATION_REASON","CLOSED_BY","CLOSED_DT","CREATED_BY","CREATED_DT","UPDATED_BY","UPDATED_DT","RN"
  from r
 where rn = 1;
