CREATE TABLE "CORE_YEARS" 
   (	"YEAR_NO" NUMBER(4,0), 
	"YEAR_LABEL" VARCHAR2(20) NOT NULL ENABLE, 
	"SEQ_NO" NUMBER, 
	"IS_ACTIVE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"REMARKS" VARCHAR2(200), 
	 CONSTRAINT "CORE_YEARS_CK1" CHECK (is_active in ('Y','N')) ENABLE, 
	 CONSTRAINT "CORE_YEARS_PK" PRIMARY KEY ("YEAR_NO")
  USING INDEX  ENABLE
   ) ;
