CREATE TABLE "FLEET_REF_CUSTODY_TYPES" 
   (	"CUSTODY_TYPE_CODE" VARCHAR2(30), 
	"CUSTODY_TYPE_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"SEQ_NO" NUMBER, 
	"IS_ACTIVE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"REMARKS" VARCHAR2(200), 
	 CONSTRAINT "FLEET_REF_CUSTODY_TYPES_CK1" CHECK (is_active in ('Y','N')) ENABLE, 
	 CONSTRAINT "FLEET_REF_CUSTODY_TYPES_PK" PRIMARY KEY ("CUSTODY_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;
