CREATE TABLE "FLEET_SIM_STATUS_MASTER" 
   (	"SIM_STATUS_CODE" VARCHAR2(30), 
	"SIM_STATUS_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"IS_ACTIVE" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"SEQ_NO" NUMBER, 
	"BADGE_CLASS" VARCHAR2(100), 
	"REMARKS" VARCHAR2(4000), 
	 CONSTRAINT "CHK_SIM_STATUS_ACTIVE" CHECK (is_active in ('Y','N')) ENABLE, 
	 PRIMARY KEY ("SIM_STATUS_CODE")
  USING INDEX  ENABLE
   ) ;
