CREATE TABLE "FLEET_SIM_OPERATORS" 
   (	"OPERATOR_CODE" VARCHAR2(30), 
	"OPERATOR_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"IS_ACTIVE" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"SEQ_NO" NUMBER, 
	"REMARKS" VARCHAR2(4000), 
	 CONSTRAINT "CHK_SIM_OPERATOR_ACTIVE" CHECK (is_active in ('Y','N')) ENABLE, 
	 PRIMARY KEY ("OPERATOR_CODE")
  USING INDEX  ENABLE
   ) ;
