CREATE TABLE "FLEET_REF_BIKE_STATUSES" 
   (	"STATUS_CODE" VARCHAR2(30), 
	"STATUS_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"SEQ_NO" NUMBER, 
	"IS_ACTIVE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"IS_ASSIGNABLE_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"IS_TERMINAL_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"STATUS_GROUP" VARCHAR2(30), 
	"REMARKS" VARCHAR2(200), 
	 CONSTRAINT "FLEET_REF_BIKE_STATUSES_CK1" CHECK (is_active in ('Y','N')) ENABLE, 
	 CONSTRAINT "FLEET_REF_BIKE_STATUSES_CK2" CHECK (is_assignable_yn in ('Y','N')) ENABLE, 
	 CONSTRAINT "FLEET_REF_BIKE_STATUSES_CK3" CHECK (is_terminal_yn in ('Y','N')) ENABLE, 
	 CONSTRAINT "FLEET_REF_BIKE_STATUSES_PK" PRIMARY KEY ("STATUS_CODE")
  USING INDEX  ENABLE
   ) ;
