CREATE TABLE "HR_APPROVAL_MODULES" 
   (	"MODULE_CODE" VARCHAR2(50), 
	"MODULE_NAME" VARCHAR2(150) NOT NULL ENABLE, 
	"IS_ACTIVE" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"SEQ_NO" NUMBER, 
	 CHECK (is_active in ('Y','N')) ENABLE, 
	 PRIMARY KEY ("MODULE_CODE")
  USING INDEX  ENABLE
   ) ;
