CREATE TABLE "HR_DOC_TYPE_MASTER" 
   (	"DOC_TYPE_CODE" VARCHAR2(40), 
	"DOC_TYPE_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"DOC_GROUP" VARCHAR2(50), 
	"IS_EXPIRY_REQUIRED" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"IS_NUMBER_REQUIRED" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"IS_ACTIVE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"SEQ_NO" NUMBER, 
	"CREATED_BY" VARCHAR2(100), 
	"CREATED_DT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100), 
	"UPDATED_DT" TIMESTAMP (6), 
	"IS_MANDATORY" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	 CONSTRAINT "CHK_DOC_TYPE_ACTIVE" CHECK (is_active in ('Y','N')) ENABLE, 
	 CONSTRAINT "CHK_DOC_TYPE_EXPIRY" CHECK (is_expiry_required in ('Y','N')) ENABLE, 
	 CONSTRAINT "CHK_DOC_TYPE_NUMBER" CHECK (is_number_required in ('Y','N')) ENABLE, 
	 PRIMARY KEY ("DOC_TYPE_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHK_DOC_TYPE_MANDATORY" CHECK (is_mandatory in ('Y','N')) ENABLE
   ) ;
