CREATE TABLE "HR_HIRING_SOURCE_MASTER" 
   (	"SOURCE_CODE" VARCHAR2(30), 
	"SOURCE_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"IS_ACTIVE" CHAR(1) DEFAULT 'Y', 
	"SEQ_NO" NUMBER, 
	 CHECK (is_active in ('Y','N')) ENABLE, 
	 PRIMARY KEY ("SOURCE_CODE")
  USING INDEX  ENABLE
   ) ;
