CREATE TABLE "HR_ORG_DOC_TYPE_MASTER" 
   (	"DOC_TYPE_CODE" VARCHAR2(40), 
	"DOC_TYPE_NAME" VARCHAR2(120) NOT NULL ENABLE, 
	"IS_EXPIRABLE" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"IS_ACTIVE" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"SEQ_NO" NUMBER, 
	"CREATED_BY" VARCHAR2(100), 
	"CREATED_DT" TIMESTAMP (0), 
	"UPDATED_BY" VARCHAR2(100), 
	"UPDATED_DT" TIMESTAMP (0), 
	 CHECK (is_expirable in ('Y','N')) ENABLE, 
	 CHECK (is_active in ('Y','N')) ENABLE, 
	 PRIMARY KEY ("DOC_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;
