CREATE TABLE "HR_PAY_MODE_MASTER" 
   (	"PAY_MODE_CODE" VARCHAR2(20), 
	"PAY_MODE_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"IS_ACTIVE" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"SEQ_NO" NUMBER, 
	"CREATED_BY" VARCHAR2(100), 
	"CREATED_DT" TIMESTAMP (0), 
	"UPDATED_BY" VARCHAR2(100), 
	"UPDATED_DT" TIMESTAMP (0), 
	 CHECK (is_active in ('Y','N')) ENABLE, 
	 PRIMARY KEY ("PAY_MODE_CODE")
  USING INDEX  ENABLE
   ) ;
