CREATE TABLE "HR_PRO_DEAL_TYPE_MASTER" 
   (	"DEAL_TYPE_CODE" VARCHAR2(40), 
	"DEAL_TYPE_NAME" VARCHAR2(150) NOT NULL ENABLE, 
	"REQUIRES_PRO_CASE" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"DEFAULT_RECOVERABLE" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"IS_ACTIVE" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"SEQ_NO" NUMBER, 
	"CREATED_BY" VARCHAR2(100), 
	"CREATED_DT" TIMESTAMP (0), 
	"UPDATED_BY" VARCHAR2(100), 
	"UPDATED_DT" TIMESTAMP (0), 
	 CHECK (requires_pro_case in ('Y','N')) ENABLE, 
	 CHECK (default_recoverable in ('Y','N')) ENABLE, 
	 CHECK (is_active in ('Y','N')) ENABLE, 
	 PRIMARY KEY ("DEAL_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;
