CREATE TABLE "HR_PRO_DEAL_INCL_MASTER" 
   (	"INCLUSION_CODE" VARCHAR2(40), 
	"INCLUSION_NAME" VARCHAR2(150) NOT NULL ENABLE, 
	"IS_ACTIVE" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"SEQ_NO" NUMBER, 
	"CREATED_BY" VARCHAR2(100), 
	"CREATED_DT" TIMESTAMP (0), 
	"UPDATED_BY" VARCHAR2(100), 
	"UPDATED_DT" TIMESTAMP (0), 
	 CHECK (is_active in ('Y','N')) ENABLE, 
	 PRIMARY KEY ("INCLUSION_CODE")
  USING INDEX  ENABLE
   ) ;
