CREATE TABLE "HR_SIM_ASSIGNMENTS" 
   (	"SIM_ASSIGN_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"SIM_ID" NUMBER NOT NULL ENABLE, 
	"EMP_ID" NUMBER NOT NULL ENABLE, 
	"ASSIGN_DT" DATE DEFAULT cast(systimestamp at time zone 'Asia/Dubai' as date) NOT NULL ENABLE, 
	"ASSIGN_REASON" VARCHAR2(50) DEFAULT 'NEW_ISSUE' NOT NULL ENABLE, 
	"ASSIGNED_BY" VARCHAR2(100), 
	"ASSIGN_REMARKS" VARCHAR2(4000), 
	"RETURN_DT" DATE, 
	"RETURN_BY" VARCHAR2(100), 
	"RETURN_REASON" VARCHAR2(50), 
	"RETURN_CONDITION" VARCHAR2(50), 
	"RETURN_REMARKS" VARCHAR2(4000), 
	"CREATED_BY" VARCHAR2(100), 
	"CREATED_DT" DATE, 
	"UPDATED_BY" VARCHAR2(100), 
	"UPDATED_DT" DATE, 
	 CONSTRAINT "CHK_HR_SIM_ASSIGN_REASON" CHECK (
            assign_reason in (
                'NEW_ISSUE',
                'ADDITIONAL_SIM',
                'REPLACEMENT',
                'PROJECT_CHANGE',
                'TEMPORARY',
                'OTHER'
            )
        ) ENABLE, 
	 CONSTRAINT "CHK_HR_SIM_RETURN_REASON" CHECK (
            return_reason is null
            or return_reason in (
                'NORMAL_RETURN',
                'LOST',
                'DAMAGED',
                'CANCELLED',
                'EMPLOYEE_EXIT',
                'OTHER'
            )
        ) ENABLE, 
	 CONSTRAINT "CHK_HR_SIM_RETURN_CONDITION" CHECK (
            return_condition is null
            or return_condition in (
                'GOOD',
                'DAMAGED',
                'LOST',
                'BLOCKED',
                'CANCELLED',
                'UNKNOWN'
            )
        ) ENABLE, 
	 PRIMARY KEY ("SIM_ASSIGN_ID")
  USING INDEX  ENABLE
   ) ;
