CREATE TABLE "SEC_USER_ROLES" 
   (	"USER_ID" NUMBER NOT NULL ENABLE, 
	"ROLE_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_SEC_USER_ROLES" PRIMARY KEY ("USER_ID", "ROLE_ID")
  USING INDEX  ENABLE
   ) ;
