CREATE TABLE "SEC_USER_PROJECTS" 
   (	"USER_ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_SEC_USER_PROJECTS" PRIMARY KEY ("USER_ID", "PROJECT_ID")
  USING INDEX  ENABLE
   ) ;
