CREATE TABLE "SEC_USER_ORGS" 
   (	"USER_ID" NUMBER NOT NULL ENABLE, 
	"ORG_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_SEC_USER_ORGS" PRIMARY KEY ("USER_ID", "ORG_ID")
  USING INDEX  ENABLE
   ) ;
