CREATE TABLE "SEC_ROLE_PERMS" 
   (	"ROLE_ID" NUMBER NOT NULL ENABLE, 
	"PERM_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_SEC_ROLE_PERMS" PRIMARY KEY ("ROLE_ID", "PERM_ID")
  USING INDEX  ENABLE
   ) ;
