ALTER TABLE "FLEET_BIKE_ACCIDENTS" ADD CONSTRAINT "FK_ACC_BIKE" FOREIGN KEY ("BIKE_ID")
	  REFERENCES "FLEET_BIKES" ("BIKE_ID") ENABLE;

ALTER TABLE "FLEET_BIKE_ACCIDENTS" ADD CONSTRAINT "FK_ACC_CHARGE" FOREIGN KEY ("EMP_CHARGE_ID")
	  REFERENCES "HR_EMP_CHARGES" ("EMP_CHARGE_ID") ENABLE;
