ALTER TABLE "FLEET_BIKES" ADD CONSTRAINT "FLEET_BIKES_CON" FOREIGN KEY ("COLOR_ID")
	  REFERENCES "FLEET_REF_COLORS" ("COLOR_ID") ENABLE;

ALTER TABLE "FLEET_BIKES" ADD CONSTRAINT "FLEET_BIKES_CON_MODEL" FOREIGN KEY ("MODEL_ID")
	  REFERENCES "FLEET_REF_MODELS" ("MODEL_ID") ENABLE;
