ALTER TABLE "FLEET_BIKE_IMPOUNDS" ADD CONSTRAINT "FLEET_BIKE_IMPOUNDS_FK1" FOREIGN KEY ("BIKE_ID")
	  REFERENCES "FLEET_BIKES" ("BIKE_ID") ENABLE;

ALTER TABLE "FLEET_BIKE_IMPOUNDS" ADD CONSTRAINT "FLEET_BIKE_IMPOUNDS_FK2" FOREIGN KEY ("IMPOUND_CUSTODY_CODE")
	  REFERENCES "FLEET_REF_CUSTODY_TYPES" ("CUSTODY_TYPE_CODE") ENABLE;

ALTER TABLE "FLEET_BIKE_IMPOUNDS" ADD CONSTRAINT "FLEET_BIKE_IMPOUNDS_FK3" FOREIGN KEY ("IMPOUND_LOCATION_ID")
	  REFERENCES "FLEET_REF_CUSTODY_LOCATIONS" ("LOCATION_ID") ENABLE;
