ALTER TABLE "FLEET_SIMS" ADD CONSTRAINT "FK_FLEET_SIMS_OPERATOR" FOREIGN KEY ("OPERATOR_CODE")
	  REFERENCES "FLEET_SIM_OPERATORS" ("OPERATOR_CODE") ENABLE;

ALTER TABLE "FLEET_SIMS" ADD CONSTRAINT "FK_FLEET_SIMS_STATUS" FOREIGN KEY ("SIM_STATUS_CODE")
	  REFERENCES "FLEET_SIM_STATUS_MASTER" ("SIM_STATUS_CODE") ENABLE;

ALTER TABLE "FLEET_SIMS" ADD CONSTRAINT "FK_FLEET_SIMS_OWNER_SUPPLIER" FOREIGN KEY ("OWNER_SUPPLIER_ID")
	  REFERENCES "FIN_SUPPLIERS" ("SUPPLIER_ID") ENABLE;
