ALTER TABLE "FLEET_BIKE_ASSIGNMENTS" ADD CONSTRAINT "FLEET_BIKE_ASSIGNMENTS_CON" FOREIGN KEY ("REF_REQUEST_ID")
	  REFERENCES "HR_BIKE_REQUESTS" ("REQUEST_ID") ENABLE;

ALTER TABLE "FLEET_BIKE_ASSIGNMENTS" ADD CONSTRAINT "FLEET_BIKE_ASSIGNMENTS_FK1" FOREIGN KEY ("BIKE_ID")
	  REFERENCES "FLEET_BIKES" ("BIKE_ID") ENABLE;
