ALTER TABLE "HR_APPROVAL_REQUESTS" ADD CONSTRAINT "FK_APPR_REQ_MODULE" FOREIGN KEY ("MODULE_CODE")
	  REFERENCES "HR_APPROVAL_MODULES" ("MODULE_CODE") ENABLE;

ALTER TABLE "HR_APPROVAL_REQUESTS" ADD CONSTRAINT "FK_APPR_REQ_RULE" FOREIGN KEY ("RULE_ID")
	  REFERENCES "HR_APPROVAL_RULES" ("RULE_ID") ENABLE;
