ALTER TABLE "HR_ASSIGNMENTS" ADD CONSTRAINT "HR_ASSIGNMENTS_JOB_ID" FOREIGN KEY ("JOB_ID")
	  REFERENCES "REF_JOBS" ("JOB_ID") ENABLE;

ALTER TABLE "HR_ASSIGNMENTS" ADD CONSTRAINT "FK_ASG_EMP" FOREIGN KEY ("EMP_ID")
	  REFERENCES "HR_EMPLOYEES" ("EMP_ID") ENABLE;

ALTER TABLE "HR_ASSIGNMENTS" ADD CONSTRAINT "FK_ASG_PROJ" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "HR_PROJECTS" ("PROJECT_ID") ENABLE;

ALTER TABLE "HR_ASSIGNMENTS" ADD CONSTRAINT "FK_ASG_CITY" FOREIGN KEY ("CITY_ID")
	  REFERENCES "REF_CITIES" ("CITY_ID") ENABLE;
