ALTER TABLE "HR_APPROVAL_RULES" ADD CONSTRAINT "FK_APPR_RULE_MODULE" FOREIGN KEY ("MODULE_CODE")
	  REFERENCES "HR_APPROVAL_MODULES" ("MODULE_CODE") ENABLE;

ALTER TABLE "HR_APPROVAL_RULES" ADD CONSTRAINT "FK_APPR_RULE_ORG" FOREIGN KEY ("ORG_ID")
	  REFERENCES "HR_ORGS" ("ORG_ID") ENABLE;
