ALTER TABLE "HR_BIKE_REQUESTS" ADD CONSTRAINT "FK_BIKE_REQ_EMP" FOREIGN KEY ("EMP_ID")
	  REFERENCES "HR_EMPLOYEES" ("EMP_ID") ENABLE;

ALTER TABLE "HR_BIKE_REQUESTS" ADD CONSTRAINT "FK_BIKE_REQ_CURRENT_BIKE" FOREIGN KEY ("CURRENT_BIKE_ID")
	  REFERENCES "FLEET_BIKES" ("BIKE_ID") ENABLE;

ALTER TABLE "HR_BIKE_REQUESTS" ADD CONSTRAINT "FK_BIKE_REQ_ASSIGNED_BIKE" FOREIGN KEY ("ASSIGNED_BIKE_ID")
	  REFERENCES "FLEET_BIKES" ("BIKE_ID") ENABLE;
