ALTER TABLE "HR_EMP_PAY_MODES" ADD CONSTRAINT "FK_EMP_PAY_MODE_EMP" FOREIGN KEY ("EMP_ID")
	  REFERENCES "HR_EMPLOYEES" ("EMP_ID") ENABLE;

ALTER TABLE "HR_EMP_PAY_MODES" ADD CONSTRAINT "FK_EMP_PAY_MODE_CODE" FOREIGN KEY ("PAY_MODE_CODE")
	  REFERENCES "HR_PAY_MODE_MASTER" ("PAY_MODE_CODE") ENABLE;
