ALTER TABLE "HR_EMP_DOCS" ADD CONSTRAINT "FK_DOCS_EMP" FOREIGN KEY ("EMP_ID")
	  REFERENCES "HR_EMPLOYEES" ("EMP_ID") ENABLE;

ALTER TABLE "HR_EMP_DOCS" ADD CONSTRAINT "FK_EMP_DOCS_DOC_TYPE" FOREIGN KEY ("DOC_TYPE")
	  REFERENCES "HR_DOC_TYPE_MASTER" ("DOC_TYPE_CODE") ENABLE;
