ALTER TABLE "HR_EMP_LOAN_TXNS" ADD CONSTRAINT "FK_LOAN_TXN_LOAN" FOREIGN KEY ("LOAN_ID")
	  REFERENCES "HR_EMP_LOANS" ("LOAN_ID") ENABLE;

ALTER TABLE "HR_EMP_LOAN_TXNS" ADD CONSTRAINT "FK_LOAN_TXN_EMP" FOREIGN KEY ("EMP_ID")
	  REFERENCES "HR_EMPLOYEES" ("EMP_ID") ENABLE;
