ALTER TABLE "HR_EMPLOYEES" ADD CONSTRAINT "HR_EMPLOYEES_HIRRING" FOREIGN KEY ("REFERENCE_SOURCE")
	  REFERENCES "HR_HIRING_SOURCE_MASTER" ("SOURCE_CODE") ENABLE;

ALTER TABLE "HR_EMPLOYEES" ADD CONSTRAINT "HR_EMPLOYEES_AGENCY" FOREIGN KEY ("AGENCY_ID")
	  REFERENCES "FIN_SUPPLIERS" ("SUPPLIER_ID") ENABLE;

ALTER TABLE "HR_EMPLOYEES" ADD CONSTRAINT "FK_EMP_NATIONALITY_COUNTRY" FOREIGN KEY ("NATIONALITY_COUNTRY_ID")
	  REFERENCES "REF_COUNTRIES" ("COUNTRY_ID") ENABLE;

ALTER TABLE "HR_EMPLOYEES" ADD CONSTRAINT "FK_EMP_AGREED_PROJ" FOREIGN KEY ("AGREED_PROJECT_ID")
	  REFERENCES "HR_PROJECTS" ("PROJECT_ID") ENABLE;

ALTER TABLE "HR_EMPLOYEES" ADD CONSTRAINT "FK_EMP_AGREED_CITY" FOREIGN KEY ("AGREED_CITY_ID")
	  REFERENCES "REF_CITIES" ("CITY_ID") ENABLE;

ALTER TABLE "HR_EMPLOYEES" ADD CONSTRAINT "FK_EMP_JOB" FOREIGN KEY ("JOB_ID")
	  REFERENCES "REF_JOBS" ("JOB_ID") ENABLE;

ALTER TABLE "HR_EMPLOYEES" ADD CONSTRAINT "FK_EMP_SUPPLIER" FOREIGN KEY ("SUPPLIER_ID")
	  REFERENCES "FIN_SUPPLIERS" ("SUPPLIER_ID") ENABLE;
