ALTER TABLE "HR_EMP_LEGAL_PROFILE" ADD CONSTRAINT "FK_EMP_LEGAL_PROFILE_EMP" FOREIGN KEY ("EMP_ID")
	  REFERENCES "HR_EMPLOYEES" ("EMP_ID") ENABLE;

ALTER TABLE "HR_EMP_LEGAL_PROFILE" ADD CONSTRAINT "FK_EMP_LEGAL_PROFILE_ORG" FOREIGN KEY ("LEGAL_ORG_ID")
	  REFERENCES "HR_ORGS" ("ORG_ID") ENABLE;
