ALTER TABLE "HR_EMP_LEGAL_STATUS_HIST" ADD CONSTRAINT "FK_LEGAL_HIST_PROFILE" FOREIGN KEY ("LEGAL_PROFILE_ID")
	  REFERENCES "HR_EMP_LEGAL_PROFILE" ("LEGAL_PROFILE_ID") ENABLE;

ALTER TABLE "HR_EMP_LEGAL_STATUS_HIST" ADD CONSTRAINT "FK_LEGAL_HIST_EMP" FOREIGN KEY ("EMP_ID")
	  REFERENCES "HR_EMPLOYEES" ("EMP_ID") ENABLE;
