ALTER TABLE "HR_ORG_DOCS" ADD CONSTRAINT "FK_HR_ORG_DOC_ORG" FOREIGN KEY ("ORG_ID")
	  REFERENCES "HR_ORGS" ("ORG_ID") ENABLE;

ALTER TABLE "HR_ORG_DOCS" ADD CONSTRAINT "FK_HR_ORG_DOC_TYPE" FOREIGN KEY ("DOC_TYPE_CODE")
	  REFERENCES "HR_ORG_DOC_TYPE_MASTER" ("DOC_TYPE_CODE") ENABLE;
