ALTER TABLE "HR_ORGS" ADD CONSTRAINT "FK_HR_ORG_PARENT" FOREIGN KEY ("PARENT_ORG_ID")
	  REFERENCES "HR_ORGS" ("ORG_ID") ENABLE;

ALTER TABLE "HR_ORGS" ADD CONSTRAINT "FK_HR_ORG_COUNTRY" FOREIGN KEY ("COUNTRY_ID")
	  REFERENCES "REF_COUNTRIES" ("COUNTRY_ID") ENABLE;
