ALTER TABLE "HR_PRO_DEALS" ADD CONSTRAINT "FK_PRO_DEAL_EMP" FOREIGN KEY ("EMP_ID")
	  REFERENCES "HR_EMPLOYEES" ("EMP_ID") ENABLE;

ALTER TABLE "HR_PRO_DEALS" ADD CONSTRAINT "FK_PRO_DEAL_ORG" FOREIGN KEY ("ORG_ID")
	  REFERENCES "HR_ORGS" ("ORG_ID") ENABLE;

ALTER TABLE "HR_PRO_DEALS" ADD CONSTRAINT "FK_PRO_DEAL_TYPE" FOREIGN KEY ("DEAL_TYPE_CODE")
	  REFERENCES "HR_PRO_DEAL_TYPE_MASTER" ("DEAL_TYPE_CODE") ENABLE;
