ALTER TABLE "HR_PRO_DEAL_INCLUSIONS" ADD CONSTRAINT "FK_DEAL_INCL_DEAL" FOREIGN KEY ("DEAL_ID")
	  REFERENCES "HR_PRO_DEALS" ("DEAL_ID") ENABLE;

ALTER TABLE "HR_PRO_DEAL_INCLUSIONS" ADD CONSTRAINT "FK_DEAL_INCL_MASTER" FOREIGN KEY ("INCLUSION_CODE")
	  REFERENCES "HR_PRO_DEAL_INCL_MASTER" ("INCLUSION_CODE") ENABLE;
