ALTER TABLE "HR_SIM_REQUESTS" ADD CONSTRAINT "FK_SIM_REQ_EMP" FOREIGN KEY ("EMP_ID")
	  REFERENCES "HR_EMPLOYEES" ("EMP_ID") ENABLE;

ALTER TABLE "HR_SIM_REQUESTS" ADD CONSTRAINT "FK_SIM_REQ_CURRENT_SIM" FOREIGN KEY ("CURRENT_SIM_ID")
	  REFERENCES "FLEET_SIMS" ("SIM_ID") ENABLE;

ALTER TABLE "HR_SIM_REQUESTS" ADD CONSTRAINT "FK_SIM_REQ_ASSIGNED_SIM" FOREIGN KEY ("ASSIGNED_SIM_ID")
	  REFERENCES "FLEET_SIMS" ("SIM_ID") ENABLE;

ALTER TABLE "HR_SIM_REQUESTS" ADD CONSTRAINT "FK_SIM_REQ_ASSIGN" FOREIGN KEY ("SIM_ASSIGN_ID")
	  REFERENCES "HR_SIM_ASSIGNMENTS" ("SIM_ASSIGN_ID") ENABLE;
