ALTER TABLE "HR_SIM_ASSIGNMENTS" ADD CONSTRAINT "FK_HR_SIM_ASSIGN_SIM" FOREIGN KEY ("SIM_ID")
	  REFERENCES "FLEET_SIMS" ("SIM_ID") ENABLE;

ALTER TABLE "HR_SIM_ASSIGNMENTS" ADD CONSTRAINT "FK_HR_SIM_ASSIGN_EMP" FOREIGN KEY ("EMP_ID")
	  REFERENCES "HR_EMPLOYEES" ("EMP_ID") ENABLE;
