ALTER TABLE "SEC_USER_ROLES" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "SEC_USERS" ("USER_ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "SEC_USER_ROLES" ADD FOREIGN KEY ("ROLE_ID")
	  REFERENCES "SEC_ROLES" ("ROLE_ID") ON DELETE CASCADE ENABLE;
