ALTER TABLE "SEC_USER_PROJECTS" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "SEC_USERS" ("USER_ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "SEC_USER_PROJECTS" ADD FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "HR_PROJECTS" ("PROJECT_ID") ENABLE;
