ALTER TABLE "SEC_USER_ORGS" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "SEC_USERS" ("USER_ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "SEC_USER_ORGS" ADD FOREIGN KEY ("ORG_ID")
	  REFERENCES "HR_ORGS" ("ORG_ID") ENABLE;
