ALTER TABLE "SEC_ROLE_PERMS" ADD FOREIGN KEY ("ROLE_ID")
	  REFERENCES "SEC_ROLES" ("ROLE_ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "SEC_ROLE_PERMS" ADD FOREIGN KEY ("PERM_ID")
	  REFERENCES "SEC_PERMS" ("PERM_ID") ON DELETE CASCADE ENABLE;
