-- ============================================================
-- Step 4 of data migration: resync every IDENTITY column's
-- underlying sequence to continue after the highest value you
-- just loaded via explicit-value INSERTs.
--
-- Without this, the next INSERT done through the app (which
-- omits the ID column and lets it auto-generate) can collide
-- with an ID you just loaded, causing a duplicate-key error.
--
-- Run this in the NEW instance's SQL Worksheet, Script mode,
-- AFTER all data is loaded (order relative to step 3 doesn't matter).
-- Uses "START WITH LIMIT VALUE" (18c+) which auto-detects the
-- correct next value from the actual data in the table.
-- ============================================================
BEGIN
  FOR c IN (
    SELECT table_name, column_name
    FROM user_tab_identity_cols
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE
        'ALTER TABLE "' || c.table_name || '" MODIFY "' || c.column_name ||
        '" GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)';
    EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('FAILED on ' || c.table_name || '.' || c.column_name ||
                              ': ' || SQLERRM);
    END;
  END LOOP;
END;
/
